//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BotProcivicaV3.ConnectionDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CasosStatus
    {
        public int idstatus { get; set; }
        public string status { get; set; }
    }
}
